### ISSUE TITLE
No remote 'conan-center' defined in remotes

### ISSUE THREAD

**Issue by BNoiZe** [Jutta-Proto/serial-snooper#1]
https://github.com/Jutta-Proto/serial-snooper/blob/2af7540db8d14165fc66a02c049be2d0f35db2a9/CMakeLists.txt#L75

Hello,
looks like it is called conancenter. I tried it compiling multiple times and it failed. After removing the dash it works. Can you verify this?

**Comment by COM8** [comment]
Confirmed and fixed. Thanks for letting me know! Forgot to update that here.
